AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/*'
    - 'Rakefile'
    - 'Gemfile'

  TargetRubyVersion: 2.3

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
    - 'app/models/*'

Style/ClassAndModuleChildren:  
  Exclude:
    - '**/*'